swifferdirtification/railsapp/config/routes.rb
Railsapp::Application.routes.draw do

  resources :dirts do
    get 'download'
    collection do
    get 'landing'
    get 'flex'
    end
  end

  
  match "redirect_to_tab" => "tab#redirect_to_tab"
  match "/tab" => "tab#index"
  root :to => 'tab#redirect_to_tab'
end

swifferdirtification/railsapp/app/models/dirt.rb
class Dirt < ActiveRecord::Base
  has_attached_file :photo, :styles => { :medium => "354x265>", :thumb => "129x100>", :share => "75x75" }
  validates_attachment_presence :photo
  #acts_as_list
end

swifferdirtification/railsapp/app/controllers/dirts_controller.rb
class DirtsController < ApplicationController
  def download
    @dirt = Dirt.find(params[:dirt_id])
    send_file "#{@dirt.photo.path(:original)}", :disposition => 'attachment'
    #, :x_sendfile=>true
  end

  # GET /dirts
  # GET /dirts.xml
  def index
    @dirts = Dirt.find(:all, :order => "created_at DESC").paginate(:page => params[:page], :per_page => 15)

    fb_uid = fb_signed_request['user_id'] if fb_signed_request
    Reportable.report(:gallery_loaded, :fb_uid => fb_uid)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dirts }
    end
  end

  def landing
    # use this for deep linking:
    if app_data['page'] && !(params[:nopage])
      redirect_to CGI::unescape(app_data['page'])
    end

    Reportable.report(:landing_loaded)
  end

  def flex

    fb_uid = fb_signed_request['user_id'] if fb_signed_request
    Rails.logger.debug fb_uid
    Reportable.report(:flex_loaded, :fb_uid => fb_uid)
    
  end

  # GET /dirts/1
  # GET /dirts/1.xml
  def show
    @dirt = Dirt.find(params[:id])
    @dirts = Dirt.all.sort {|a,b| b.id <=> a.id }

    fb_uid = fb_signed_request['user_id'] if fb_signed_request
    Reportable.report(:show_loaded, :fb_uid => fb_uid)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dirt }
    end
  end

  # GET /dirts/new
  # GET /dirts/new.xml
  def new
    @dirt = Dirt.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dirt }
    end
  end

  # GET /dirts/1/edit
  def edit
    @dirt = Dirt.find(params[:id])
  end

  # POST /dirts
  # POST /dirts.xml
  def create
    @dirt = Dirt.new(params[:dirt])

    fb_uid = fb_signed_request['user_id'] if fb_signed_request
    Reportable.report(:image_upload, :fb_uid => fb_uid)

    respond_to do |format|
      if @dirt.save
        format.html { redirect_to(@dirt, :notice => 'Dirt was successfully created.') }
        format.xml  { render :xml => @dirt, :status => :created, :location => @dirt }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dirt.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dirts/1
  # PUT /dirts/1.xml
  def update
    @dirt = Dirt.find(params[:id])

    respond_to do |format|
      if @dirt.update_attributes(params[:dirt])
        format.html { redirect_to(@dirt, :notice => 'Dirt was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dirt.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dirts/1
  # DELETE /dirts/1.xml
  def destroy
    @dirt = Dirt.find(params[:id])
    @dirt.destroy

    respond_to do |format|
      format.html { redirect_to(dirts_url) }
      format.xml  { head :ok }
    end
  end
end

swifferdirtification/railsapp/app/helpers/dirts_helper.rb
module DirtsHelper
end

swifferdirtification/railsapp/app/views/dirts/_form.html.erb
<%= form_for(@dirt, :html => { :multipart => true }) do |f| %>
  <% if @dirt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dirt.errors.count, "error") %> prohibited this dirt from being saved:</h2>

      <ul>
      <% @dirt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :photo %><br/>
    <%= image_tag @dirt.photo.url(:thumb) unless @dirt.new_record? %><br/>
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

swifferdirtification/railsapp/app/views/dirts/_share.html.erb
    <% facebook_share_button_vo = Facebook_share_button_vo.new %>
    <% facebook_share_button_vo.name = "Get Dirtified." %>
    <% facebook_share_button_vo.link = "#{bounce_url}?page=" + CGI::escape("/dirts/landing") %>
    <% facebook_share_button_vo.description = "If you were in a Swiffer commericial, what would you look like? Find out." %>
    <% #facebook_share_button_vo.picture = "#{app_host}#{@dirt.photo.url(:share)}" %>
    <script language="javascript">
      function shareCallback (post_id, exception) {
        if(exception) {
          alert(exception);
        }
      }
    </script>
    <%= facebook_share_button "",facebook_share_button_vo,"shareCallback","share-button" %>

swifferdirtification/railsapp/app/views/dirts/_share_my_dirt.html.erb
    <% facebook_share_button_vo = Facebook_share_button_vo.new %>
    <% facebook_share_button_vo.name = "I've been Dirtified." %>
    <% facebook_share_button_vo.link = "#{bounce_url}?page=" + CGI::escape("/dirts/#{@dirt.id}") %>
    <% facebook_share_button_vo.description = "If you were in a Swiffer commericial, what would you look like? Find out." %>
    <% facebook_share_button_vo.picture = "#{app_host}#{@dirt.photo.url(:share)}" %>
    <script language="javascript">
      function shareCallback (post_id, exception) {
        if(exception) {
          alert(exception);
        }
      }
    </script>
    <%= facebook_share_button "",facebook_share_button_vo,"shareCallback","share-button" %>

swifferdirtification/railsapp/app/views/dirts/edit.html.erb
<h1>Editing dirt</h1>

<%= render 'form' %>

<%= link_to 'Show', @dirt %> |
<%= link_to 'Back', dirts_path %>

swifferdirtification/railsapp/app/views/dirts/flex.html.erb
<div class="background">
  <%= link_to '', landing_dirts_path, :class => 'home-button' %>
  <%= link_to '', dirts_path, :class => 'gallery-button' %>
  <%= render 'share' %>
  
  <div style="width:480px; height:650px; position:absolute; top:130px; left:20px;">
    <div id="flashContent">
      <!-- <object width="480" height="640">
              <param name="movie" value="<%= "#{app_host}/swf/Main.swf?" + DateTime.now.to_i.to_s %>">
              <param name="wmode" value="transparent">
              <param name="allowscriptaccess" value="always">
              <param name="flashvars" value="<%= "app_host=#{app_host}&app_id=#{app_id}&access_token=#{app_access_token}" %>">
              <embed src="<%= "#{app_host}/swf/Main.swf?" + DateTime.now.to_i.to_s %>" width="480" height="640" wmode="transparent" allowscriptaccess="always" flashvars="<%= "app_host=#{app_host}&app_id=#{app_id}&access_token=#{app_access_token}" %>">
              </embed>
            </object> -->
    </div>
    
    <script type="text/javascript">
      var flashvars = {
        app_host: "<%= "#{app_host}" %>",
        app_id: "<%= "#{app_id}" %>",
        access_token: "<%= "#{app_access_token}" %>"
      };
      
		
			swfobject.embedSWF("<%= "#{app_host}/swf/Main.swf?" + DateTime.now.to_i.to_s %>", "flashContent", "480", "650", "10.0", null, flashvars, null, {name:"flashContent",wmode:"transparent"}); 			
		</script>
    
    <!-- <%= link_to 'show.html', dirt_path(1), :class => '' %> -->
  </div>
  
   

</div>

swifferdirtification/railsapp/app/views/dirts/index.html.erb
<div class="background">
  <%= link_to '', landing_dirts_path, :class => 'home-button' %>
  <%= link_to '', dirts_path, :class => 'gallery-button' %>
  <%= render 'share' %>
  
  <img src="/images/gallery_headline.png" width="206" height="39" style="position:absolute; top:130px; left:158px;" />

  <div class="green-container" style="position: absolute; top: 175px; left: 40px; width:420px; height:538px;">

    <table width="100%" cellspacing="5px">
       <tr>
         <% for i in 0 .. 14 do %>
           <% dirt = @dirts[i] %>
           <td class="dirts-thumb-container">
             <% if dirt %>
               <%= link_to (image_tag dirt.photo.url(:thumb), :class => 'dirts-thumb'), dirt_path(dirt) %>
             <% end %>
           </td>
         <% if i != 0 && ((i+1) % 3) == 0 %>
      </tr> 
      <tr>
         <% end %>
     <% end %>
       </tr>
    </table>
    

  </div>
  
  <%= will_paginate @dirts %>
    
</div>

swifferdirtification/railsapp/app/views/dirts/landing.html.erb
<div class="background">
   <%= link_to '', landing_dirts_path, :class => 'home-button' %>
   <%= link_to '', dirts_path, :class => 'gallery-button' %>
   <%= render 'share' %>
   
   <img src="/images/landing_page_toptext.png" width="401" height="63" style="position:absolute; top:136px; left:58px;" />
   <img src="/images/landing_page_photos.png" width="450" height="239" style="position:absolute; top:216px; left:36px;" />
   <%= link_to '', '#', :class => 'dirtmyself-button', :id => 'dirtmyself-button' %>

<script type='text/javascript'>
  fbReady(function() {
    $('#dirtmyself-button').click(function() {
      requestPermission('publish_stream, user_photos', permissionCallback);
      
    });
  });

  function permissionCallback(response) {
    if(response.installed == 1) {
      window.parent.location = "<%="#{bounce_url}?page=" + CGI::escape("/dirts/flex") %>";
    } else {
      FB.getLoginStatus(function(response) {
        if(response.session) {
      window.parent.location = "<%="#{bounce_url}?page=" + CGI::escape("/dirts/flex") %>";
        }
      });
    }
  }
</script>

   <img src="/images/landing_page_mudgirl.png" width="161" height="269" style="position:absolute; top:516px; left:36px;" />
   <img src="/images/landing_page_quote.png" width="200" height="24" style="position:absolute; top:599px; left:143px;" />
  
   <div class="footer-text">
     <a href="http://www.pg.com/privacy/english/privacy_notice.html" target="_blank">privacy policy</a>
   </div>

   <div id="terms_and_conditions" class="hidden">

   </div>
</div>

swifferdirtification/railsapp/app/views/dirts/new.html.erb
<h1>New dirt</h1>

<%= render 'form' %>

swifferdirtification/railsapp/app/views/dirts/show.html.erb
<div class="background">
  <%= link_to '', landing_dirts_path, :class => 'home-button' %>
  <%= link_to '', dirts_path, :class => 'gallery-button' %>
  <%= render 'share_my_dirt' %>
  
  <img src="/images/results_headline.png" width="406" height="35" style="position:absolute; top:136px; left:58px;" />
  <div class="green-container" style="position: absolute; top: 194px; left: 71px;">
    <img src="/images/results_photo_headline.png" width="129" height="19" style="padding: 0 0 5px 106px" />
    <!--
    Do not remove or modify the following hidden field. It is parsed by the Flex app.
    -->
    <input type="hidden" name="dirt_id" value="<%= @dirt.id %>"/>
    <div style='height: 265px; width:354px; text-align: center;'>
      <%= image_tag @dirt.photo.url(:medium) %>
      <div class="post-button-wrapper">
        <% facebook_share_button_vo = Facebook_share_button_vo.new %>
        <% facebook_share_button_vo.name = "I've been Dirtified." %>
        <% facebook_share_button_vo.link = "#{bounce_url}?page=" + CGI::escape("/dirts/#{@dirt.id}") %>
        <% facebook_share_button_vo.description = "If you were in a Swiffer commericial, what would you look like? Find out." %>
        <% facebook_share_button_vo.picture = "#{app_host}#{@dirt.photo.url(:share)}" %>
        <script language="javascript">
          function shareCallback (post_id, exception) {
            if(exception) {
              alert(exception);
            }
          }
        </script>
        <%= facebook_share_button "",facebook_share_button_vo,"shareCallback","post-button" %>
      </div>
    </div>
  </div>
  
  <%= link_to '', dirt_download_path(@dirt), :class => 'download-button' %>
  <%= link_to '', landing_dirts_path, :class => 'start-over-button' %>
  
  <div class="green-container" style="position: absolute; top: 575px; left: 40px; width:420px;">
     <img src="/images/results_photo_gallery_headline.png" width="232" height="19" style="padding: 0 0 5px 106px" />

      <table width="100%" cellspacing="5px">
        <tr>
         <% for i in 0 .. 2 do %>
           <% dirt = @dirts[i] %>
           <td class="dirts-thumb-container">
             <% if dirt %>
               <%= link_to (image_tag dirt.photo.url(:thumb), :class => 'dirts-thumb'), dirt_path(dirt) %>
             <% end %>
           </td>
     <% end %>
       </tr> 
     </table>
     
  </div>
  
  <%= link_to '', dirts_path, :class => 'visit-gallery-button' %>
  
</div>