swifferdirtification/railsapp/config/routes.rb
Railsapp::Application.routes.draw do

  resources :dirts do
    get 'download'
    collection do
    get 'landing'
    get 'flex'
    end
  end

  
  match "redirect_to_tab" => "tab#redirect_to_tab"
  match "/tab" => "tab#index"
  root :to => 'tab#redirect_to_tab'
end

swifferdirtification/railsapp/app/models/tab.rb
class Tab < ActiveRecord::Base
end

swifferdirtification/railsapp/app/controllers/tab_controller.rb
class TabController < ApplicationController
  
  def index
    @access_token = app_access_token
    @ref = app_data['ref'] || nil

    # use this for fangating:
    if !fan?
      Reportable.report(:fangate_loaded)
      render 'fangate'
    else
      redirect_to landing_dirts_path
    end
  end
  
  def redirect_to_tab
    # => Forward params
    @params = params
  end
  
  def register_callback
  end

end

swifferdirtification/railsapp/app/helpers/tabs_helper.rb
module TabsHelper
end

swifferdirtification/railsapp/app/views/tab/_form.html.erb
<%= form_for(@tab) do |f| %>
  <% if @tab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tab.errors.count, "error") %> prohibited this tab from being saved:</h2>

      <ul>
      <% @tab.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

swifferdirtification/railsapp/app/views/tab/edit.html.erb
<h1>Editing tab</h1>

<%= render 'form' %>

<%= link_to 'Show', @tab %> |
<%= link_to 'Back', tabs_path %>

swifferdirtification/railsapp/app/views/tab/fangate.html.erb
<div id="fangate">
   <img src="images/like_us_banner.jpg" width="520" height="351" />
</div>

swifferdirtification/railsapp/app/views/tab/index.html.erb
<h1>Listing tabs</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tabs.each do |tab| %>
  <tr>
    <td><%= link_to 'Show', tab %></td>
    <td><%= link_to 'Edit', edit_tab_path(tab) %></td>
    <td><%= link_to 'Destroy', tab, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tab', new_tab_path %>

swifferdirtification/railsapp/app/views/tab/new.html.erb
<h1>New tab</h1>

<%= render 'form' %>

<%= link_to 'Back', tabs_path %>

swifferdirtification/railsapp/app/views/tab/redirect_to_tab.html.erb
<img src="/images/loading-spinner.gif"/>
<script language="javascript">
  $('#fb-root').bind('fb-init', function(event) {
    window.parent.location = '<%="#{fb_redirect_to_tab_url}&app_data=#{CGI.escape @params.to_json}".html_safe%>';
    //console.log("yo");
  });
</script>

swifferdirtification/railsapp/app/views/tab/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_tab_path(@tab) %> |
<%= link_to 'Back', tabs_path %>